site_name: MAPPING UKRAINIAN SACRAL WOODEN ARCHITECTURAL HERITAGE | MUSWAH
theme:
  name: material
  icon: 
    logo: material/content-save-check
  palette: 
    scheme: slate
nav:
    - Home: index.md
    - Get Involved: get-involved.md
    - Contributors: contributors.md
extra_css:
  - stylesheets/extra.css
