site_name: MUSWAH
theme:
  name: material
  icon: 
    logo: material/content-save-check
  favicon: img/content-save-check.png
  # palette: 
  #   scheme: slate
nav:
    - Home: index.md
    - Contributors: contributors.md
    # - Resources: resources.md
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list

